---
name: Terraform Linter

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]

jobs:
  terraform-linter:
    name: Check Terraform code for common mistakes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true